title: tbolt
tagline: UI Design & Programming

pages:
  - { name: "About", url: "about" }
  - { name: "Contact", url: "contact" }

social:
  - { icon: "github", link: "https://www.github.com/tbolt" }
